### ISSUE TITLE
Create File Upload component

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/ui-components#28]
~File upload component should allow user to select multiple files from their computer to be uploaded. As files are uploaded, the thumbnails and names are displayed next to the upload control. If thumbnail is not available (e.g. unsupported file type), a file type icon (if recognized; if not - generic) should be displayed.~ 
UPD.: See next [comment](https://github.com/cardstack/ui-components/issues/28#issuecomment-489716100) for updated description and wireframes

**Comment by nicholas02261987** [comment]
The description is not accurate. 

The user can upload documents from their desktop (by clicking add to get a modle / or by dragging to the form field). If just one document is added, the user is shown a preview of that document (if possible - if not possible it skips this step). The user can view the document and then choose to attached this document to the form (this is not the form submission) or remove the document and upload a new one.

If the user decided the document is correct and attaches it to the form field - they will then see a thumbnail, date, file type and title of the document with options to view, remove, or add document to their library and make it a card (some meta data can also be shown). 

<img width="1162" alt="single document" src="https://user-images.githubusercontent.com/48684509/57244760-20453800-7007-11e9-8e88-219a380ead98.png">

If the user uploads more than one document - rather than seeing a preview of the document they are taking to a screen like the attached "multi docuemnt". Here the user sees a thumbnail, title, meta data, file type.... and the ability to view the file, remove the file or add them to their library as cards. From this the user can attache the group of documents to the form field.

<img width="1179" alt="multi document" src="https://user-images.githubusercontent.com/48684509/57244761-20453800-7007-11e9-87fc-304445adfeef.png">
